### PR TITLE
Include Bitcode in iOS builds

### LINKED ISSUE #98: Package should include Bitcode
After updating to Xcode 7 GM, packager still works great (:smile:).

One notable exception is that there is no bitcode included in the resulting framework. This leads to the issue discussed on SO [here](http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled).

For now I am working around this by adding this line to my podspec:

```
s.pod_target_xcconfig = { 'OTHER_CFLAGS' => '-fembed-bitcode' }
```

However, I think packager should include built in support for this, since it is on by default in Xcode 7.

I will try to take the time to write up a PR later in the week. Its proving a little trickier than I originally thought.

### PR DESCRIPTION
**Pull request by jtreanor**
This fixes #98.

Some useful reading: https://forums.developer.apple.com/thread/17529, http://www.openradar.me/21884601, https://forums.developer.apple.com/thread/3971

~~There is one very pesky known issue. Any framework built through this with mangling enabled gives tons of errors like this:~~

screen_shot_2015-09-22_at_16 33 48

~~This happens only if "Debug Information Format" is set to "DWARF with dSYM File". (We are seeing this issue in https://github.com/intercom/intercom-ios/issues/97).~~

~~If mangling is disabled the warnings go away (but of course we need mangling). Any ideas would be greatly appreciated.~~

(See comment below; this issue is unrelated).

### CODE REVIEW

File: lib/cocoapods-packager/builder.rb [hunk 1]
```diff
@@ -93,14 +89,15 @@ def compile(platform)
       defines = "GCC_PREPROCESSOR_DEFINITIONS='PodsDummy_Pods_#{@spec.name}=PodsDummy_PodPackage_#{@spec.name}'"
       defines << " " << @spec.consumer(platform).compiler_flags.join(' ')
 
+      options = ""
       if platform.name == :ios
-        defines = "#{defines} ARCHS=\"x86_64 i386 arm64 armv7 armv7s\""
+        options = "ARCHS=\"arm64 armv7 armv7s\" OTHER_CFLAGS=\"-fembed-bitcode\""
```
Comment (jtreanor) [inline lib/cocoapods-packager/builder.rb]: Only include Bitcode for device archs

File: lib/cocoapods-packager/symbols.rb [hunk 2]
```diff
@@ -3,7 +3,9 @@ def symbols_from_library(library)
     syms = `nm -gU #{library}`.split("\n")
 
     result = classes_from_symbols(syms)
-    result + constants_from_symbols(syms)
+    result = result + constants_from_symbols(syms)
+
+    result.reject { |e| e == "llvm.cmdline" || e == "llvm.embedded.module" }
```
Comment (jtreanor) [inline lib/cocoapods-packager/symbols.rb]: We need to make sure these symbols don't get mangled.

**Comment by jtreanor** [comment]
I'm not sure why the specs are failing on Travis; they all pass locally for me.

File: spec/command/package_spec.rb [hunk 3]
```diff
@@ -73,10 +73,39 @@ module Pod
...
 
+      it "includes Bitcode for device arch slices when packaging an iOS Pod" do
+        SourcesManager.stubs(:search).returns(nil)
+
+        command = Command.parse(%w{ package spec/fixtures/NikeKit.podspec })
+        command.run
+
+        lib = Dir.glob("NikeKit-*/ios/NikeKit.framework/NikeKit").first
+
+        #Check for __LLVM segment in each device architecture
```
Comment (jtreanor) [inline spec/command/package_spec.rb]: According to https://forums.developer.apple.com/thread/3971, this is the best way to check for a Bitcode segment.

**Comment by neonichu** [comment]
Thanks for this!

One issue with Travis is that we need to switch to Xcode 7 to get bitcode support: <https://travis-ci.org/CocoaPods/cocoapods-packager/builds/81614635#L288>

**Comment by kcoleman731** [comment]
I've been looking at adding bitcode as well on my dynamic frameworks pr. @jtreanor from one of the articles you reference above (https://forums.developer.apple.com/thread/3971), it looks like bitcode is only added to a framework via an archive build. Am I reading this wrong?

Also FWIW, the way I have been enabling bitcode is by adding `ENABLE_BITCODE` to the target build settings in pod_utils.rb. 

```
        unless static_installer.nil?
          static_installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
              config.build_settings['ENABLE_BITCODE'] = 'YES'
            end
          end
```

**Comment by jtreanor** [comment]
@kcoleman731 I believe Bitcode is produced by default in an archive build but also if you provide the `-fembed-bitcode` flag. I believe this is correct because the binaries I am producing do contain Bitcode.

However, I will try archiving in case that is the source of the issue.

**Comment by jtreanor** [comment]
If I run the `strings Output.framework/Versions/A/Output | grep llvm` on any binary created through Packager (either the current release or this PR), I always get output looking something like this:

```
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/UIKit-27PL4RA7HR3WK.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/Foundation-2NNP27CGK7J4W.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/UIKit-27PL4RA7HR3WK.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/Darwin-N0EKDJGHFAYB.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/Foundation-2NNP27CGK7J4W.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/UIKit-27PL4RA7HR3WK.pcm
/var/folders/p8/vsv9nj656rs8gc8pbf7kv8cc0000gn/C/org.llvm.clang/ModuleCache/3FRT1VOOXIFIP/Foundation-2NNP27CGK7J4W.pcm
...
```

These are directories and the machine that it was built on. @neonichu Why does the binary contain references to _my_ ModuleCache? I seems like Xcode now wants to use them for something.

**Comment by jtreanor** [comment]
Just a quick update here. The warnings I posted above are actually _completely unrelated to these changes. I am also seeing them when building with 1.3.0 and Xcode 7. They do not occur when the framework is built with Xcode 6.

So these changes are good to go as far as I'm aware.

**Comment by neonichu** [comment]
@jtreanor could you update the travis config to use Xcode 7?

**Comment by jtreanor** [comment]
@neonichu Sure, I'll do that now.

**Comment by jtreanor** [comment]
All specs are passing on Travis now :smile:

**Comment by neonichu** [comment]
Awesome :+1: 

Thanks for the contribution!

File: lib/cocoapods-packager/builder.rb (hunk 1 above)
Comment (segiddins) [inline lib/cocoapods-packager/builder.rb]: This should also be for watchos and tvos?
