### PR TITLE
Catch build errors during `pod package`.

### LINKED ISSUE #47: Pod package does not fail when xcodebuild fails
I ran into an into issue where symbols were missing from my packaged pod.

I tracked it down to ```xcodebuild``` failing (https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/builder.rb#L149). However, the ```pod package``` command appeared as though it ran successfully. It would be great if the return code of xcodebuild is checked for success, and a way to see the xcodebuild output when a failure occurs.

### PR DESCRIPTION
**Pull request by michaelmelanson**
This pull request fixes #47 by throwing an exception when `xcodebuild` commands fail.

There's no automated tests accompanying this, but the surrounding code is also untested. I'm open to suggestions about the best way to approach adding tests.

### CODE REVIEW

File: lib/cocoapods-packager/builder.rb [hunk 1]
```diff
@@ -174,7 +184,13 @@ def static_libs_in_sandbox(build_dir = 'build')
     end
 
     def xcodebuild(defines = '', args = '', build_dir = 'build')
-      `xcodebuild #{defines} CONFIGURATION_BUILD_DIR=#{build_dir} clean build #{args} -configuration Release -target Pods -project #{@sandbox_root}/Pods.xcodeproj 2>&1`
+      command = "xcodebuild #{defines} CONFIGURATION_BUILD_DIR=#{build_dir} clean build #{args} -configuration Release -target Pods -project #{@sandbox_root}/Pods.xcodeproj 2>&1"
+      log = []
+      `#{command}`.lines.each { |line| log << line }
```
Comment (segiddins) [inline lib/cocoapods-packager/builder.rb]: `log = `#{command}`.lines.to_a`?

File: lib/pod/command/package.rb [hunk 2]
```diff
@@ -67,10 +67,19 @@ def build_in_sandbox(platform)
...
-
-        Pathname.new(config.sandbox_root).rmtree
-        FileUtils.rm_f('Podfile.lock')
+        begin
+          perform_build(platform, sandbox)
+
+        rescue Pod::Builder::BuildFailedException => ex
+          puts "Build command failed: #{ex.command}"
+          puts "Output:"
+          ex.output.each { |line| puts "    #{line}" }
```
Comment (segiddins) [inline lib/pod/command/package.rb]: `puts line.map { |l| '    ' << line }`

File: lib/cocoapods-packager/builder.rb (hunk 1 above)
Comment (michaelmelanson) [inline lib/cocoapods-packager/builder.rb]: Sure, will make that change.

File: lib/pod/command/package.rb (hunk 2 above)
Comment (michaelmelanson) [inline lib/pod/command/package.rb]: I don't understand. Those don't seem to mean the same thing to me.

File: lib/pod/command/package.rb [hunk 3]
```diff
@@ -67,10 +67,19 @@ def build_in_sandbox(platform)
...
+          Process.exit
```
Comment (neonichu) [inline lib/pod/command/package.rb]: Considering this, we might just as well exit directly where the build fails, avoiding a bunch of additional code.

Comment (michaelmelanson) [inline lib/pod/command/package.rb]: Coming back to this today, I agree. I'll move the code in this `rescue` block into `Builder`.

File: lib/cocoapods-packager/builder.rb [hunk 4]
```diff
@@ -1,5 +1,15 @@
 module Pod
   class Builder
+    class BuildFailedException < RuntimeError
```
Comment (neonichu) [inline lib/cocoapods-packager/builder.rb]: This is no longer used.

File: lib/pod/command/package.rb [hunk 5]
```diff
@@ -67,10 +67,13 @@ def build_in_sandbox(platform)
 
         sandbox = install_pod(platform.name)
 
-        perform_build(platform, sandbox)
```
Comment (neonichu) [inline lib/pod/command/package.rb]: This change is no longer needed.

Comment (michaelmelanson) [inline lib/pod/command/package.rb]: Correct me if I'm wrong here, but don't we need to wrap lines 74-75 in an `ensure` block so that they're cleaned up even if the build fails?

File: lib/cocoapods-packager/builder.rb (hunk 4 above)
Comment (michaelmelanson) [inline lib/cocoapods-packager/builder.rb]: Oops, good point.

File: lib/pod/command/package.rb (hunk 5 above)
Comment (neonichu) [inline lib/pod/command/package.rb]: The `ensure` block will only be ran in case of exceptions, though, not when we exit the process. Might be better to throw an `InformationalError` from `xcodebuild` - then we would hit the `ensure` block.

Comment (michaelmelanson) [inline lib/pod/command/package.rb]: I used `Process.exit`, rather than `Process.exit!`, because it works by throwing a `SystemExit` exception which unwinds the stack up to the root -- firing `ensure` blocks and exit handlers along the way -- before terminating the process. So the `ensure` block will be called here, and I've verified that by adding a debug message there.

See http://ruby-doc.org/core-1.9.3/Process.html#method-c-exit

Comment (neonichu) [inline lib/pod/command/package.rb]: Ah, sorry, didn't know about that.

Comment (michaelmelanson) [inline lib/pod/command/package.rb]: No worries. It's a bit subtle, so I'll add a comment there.

File: lib/cocoapods-packager/builder.rb [hunk 6]
```diff
@@ -174,7 +174,15 @@ def static_libs_in_sandbox(build_dir = 'build')
     end
 
     def xcodebuild(defines = '', args = '', build_dir = 'build')
-      `xcodebuild #{defines} CONFIGURATION_BUILD_DIR=#{build_dir} clean build #{args} -configuration Release -target Pods -project #{@sandbox_root}/Pods.xcodeproj 2>&1`
+      command = "xcodebuild #{defines} CONFIGURATION_BUILD_DIR=#{build_dir} clean build #{args} -configuration Release -target Pods -project #{@sandbox_root}/Pods.xcodeproj 2>&1"
+      output = `#{command}`.lines.to_a
+
+      if $?.exitstatus != 0
+        puts "Build command failed: #{command}"
+        puts "Output:"
```
Comment (neonichu) [inline lib/cocoapods-packager/builder.rb]: Let's wrap these two into something like this <https://github.com/CocoaPods/CocoaPods/blob/546b1252802d04b3a4b111aae90661f2bb9c4c82/lib/cocoapods/command.rb#L59> and this should be good to merge!

**Comment by neonichu** [comment]
As for testing this, adding a fixture spec with refers a file with a syntax error should allow us to trigger the error and then we could compare the output against known good one. `Process.exit` should be stubbed out.

**Comment by neonichu** [comment]
cool, cool, cool - thanks for this!
